DROP SCHEMA IF EXISTS MAIS2023;
CREATE SCHEMA MAIS2023;
USE MAIS2023;
DROP TABLE IF EXISTS JOBS;
CREATE TABLE JOBS (
	JOB_ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    YEARS_OF_EXPERIENCE INT
);
DROP TABLE IF EXISTS RESUMES;
CREATE TABLE RESUMES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    JOB_ID INT,
    PDF_DATA LONGBLOB,
    FOREIGN KEY (JOB_ID) REFERENCES Jobs(JOB_ID)
);