DROP SCHEMA IF EXISTS MAIS2023;
CREATE SCHEMA MAIS2023;
USE MAIS2023;
DROP TABLE IF EXISTS JOBS;
CREATE TABLE JOBS (
	JOB_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(10000) NOT NULL,
    LEVEL VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    SKILLS VARCHAR(1000)
);
DROP TABLE IF EXISTS RESUMES;
CREATE TABLE RESUMES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    JOB_ID INT,
    PDF_DATA VARCHAR(1500),
    SIMILARITY_SCORE FLOAT,
    FOREIGN KEY (JOB_ID) REFERENCES Jobs(JOB_ID)
);