DROP SCHEMA IF EXISTS APPLICRUITER;
CREATE SCHEMA APPLICRUITER;
USE APPLICRUITER;
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTH_ID VARCHAR(255) UNIQUE,   
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    EMAIL_VERIFIED TINYINT(1) DEFAULT 0,
    LAST_NAME VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    PICTURE VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP
);
DROP TABLE IF EXISTS ORGANIZATIONS;
CREATE TABLE ORGANIZATIONS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    OWNER INT NOT NULL,
    ADDRESS VARCHAR(255),
    COUNTRY VARCHAR(255),
    CITY VARCHAR(255),
    LOGO VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    FOREIGN KEY (OWNER) REFERENCES USERS(ID) ON DELETE CASCADE
);
DROP TABLE IF EXISTS JOBS;
CREATE TABLE JOBS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ORG INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(10000) NOT NULL,
    LEVEL VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    SKILLS VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    FOREIGN KEY (ORG) REFERENCES ORGANIZATIONS(ID) ON DELETE CASCADE
);
DROP TABLE IF EXISTS RESUMES;
CREATE TABLE RESUMES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    JOB_ID INT,
    PDF_DATA VARCHAR(1500),
    SIMILARITY_SCORE FLOAT,
    FOREIGN KEY (JOB_ID) REFERENCES Jobs(ID) ON DELETE CASCADE
);
DROP TABLE IF EXISTS USER_ORGANIZATIONS;
CREATE TABLE USER_ORGANIZATIONS (
	USER_ID INT,
    ORG_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATIONS(ID) ON DELETE CASCADE
);
DELIMITER //
CREATE TRIGGER after_org_insert
AFTER INSERT
ON organizations FOR EACH ROW
BEGIN
    INSERT INTO USER_ORGANIZATIONS (USER_ID, ORG_ID)
    VALUES (NEW.OWNER, NEW.ID);
END //
DELIMITER ;